name: Deploy Supabase migrations to Staging

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      DB_PASSWORD: ${{ secrets.SUPABASE_STAGING_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_STAGING_PROJECT_ID }}
    
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          supabase link --project-ref $PROJECT_ID
          supabase db push
